// apps/context/output/svelte/src/Child.svelte
<script context="module" lang="ts">
  type Props = {
    message: string;
  };
</script>

<script lang="ts">
  import { getContext, setContext } from "svelte";

  import Context from "./custom.context.js";

  export let message: Props["message"];

  let foo = getContext(Context.key);
  setContext(Context.key, {
    foo: "child",
    content() {
      return message;
    },
  });

  let name = "Child";
</script>

<div>
  {message || "Hello"}
  {name}! I am a Child component.
  {foo.foo}
</div>

// apps/context/output/react/src/Child.tsx
import * as React from "react";
import { useState, useContext } from "react";

type Props = {
  message: string;
};
import Context from "./custom.context.js";

export default function ChildComponent(props: Props) {
  const [name, setName] = useState(() => "Child");

  const foo = useContext(Context);

  return (
    <Context.Provider
      value={{
        foo: "child",

        content() {
          return props.message;
        },
      }}
    >
      <div>
        {props.message || "Hello"}
        {name}! I am a Child component.
        {foo.foo}
      </div>
    </Context.Provider>
  );
}
