// apps/context/output/svelte/src/Parent.svelte
<script context="module" lang="ts">
  type Props = {
    message: string;
  };
</script>

<script lang="ts">
  import { getContext, setContext } from "svelte";

  import Context from "./custom.context.js";
  import ChildComponent from "./Child.svelte";

  export let message: Props["message"];

  let foo = getContext(Context.key);
  setContext(Context.key, {
    foo: "parent",
    content() {
      return message;
    },
  });

  let name = "Parent";
</script>

<div>
  {message || "Hello"}
  {name}! I am a Parent Component.
  <ChildComponent message="Hi" />
  {foo.foo}
</div>

// apps/context/output/react/src/Parent.tsx
import * as React from "react";
import { useState, useContext } from "react";

type Props = {
  message: string;
};
import Context from "./custom.context.js";
import ChildComponent from "./Child.lite";

export default function ParentComponent(props: Props) {
  const [name, setName] = useState(() => "Parent");

  const foo = useContext(Context);

  return (
    <Context.Provider
      value={{
        foo: "parent",

        content() {
          return props.message;
        },
      }}
    >
      <div>
        {props.message || "Hello"}
        {name}
        ! I am a Parent Component.
        <ChildComponent message="Hi" />
        {foo.foo}
      </div>
    </Context.Provider>
  );
}
