// apps/show/output/react/src/Parent.tsx
import * as React from "react";
import { useState } from "react";

type Props = {
  message: string;
};
import ChildComponent from "./Child.lite";

export default function ParentComponent(props: Props) {
  const [name, setName] = useState(() => "Parent");

  return (
    <div>
      {props.message || "Hello"}
      {name}! I am a Parent Component.
      {name === "Parent" ? (
        <>
          <ChildComponent message="Hi" />
        </>
      ) : null}
    </div>
  );
}

// apps/vue-composition/output/vue/vue3/src/Parent.vue
<template>
  <div>
    {{ message || "Hello" }} {{ name }}! I am a Parent Component.
    <child-component message="Hi"></child-component>
  </div>
</template>

<script setup lang="ts">
import { ref } from "vue";
type Props = {
  message: string;
};

import ChildComponent from "./Child.vue";

const props = defineProps<Props>();
const name = ref("Parent");
</script>
