// apps/typescript-output/output/svelte/src/Parent.svelte
<script context="module" lang="ts">
  type Props = {
    message: string;
  };
</script>

<script lang="ts">
  import ChildComponent from "./Child.svelte";

  export let message: Props["message"];

  let name = "Parent";
</script>

<div>
  {message || "Hello"}
  {name}! I am a Parent Component.
  <ChildComponent message="Hi" />
</div>

// apps/vue-composition/output/vue/vue3/src/Parent.vue
<template>
  <div>
    {{ message || "Hello" }} {{ name }}! I am a Parent Component.
    <child-component message="Hi"></child-component>
  </div>
</template>

<script setup lang="ts">
import { ref } from "vue";
type Props = {
  message: string;
};

import ChildComponent from "./Child.vue";

const props = defineProps<Props>();
const name = ref("Parent");
</script>
