// apps/typescript-output/output/vue/vue3/src/Parent.vue
<template>
  <div>
    {{ message || "Hello" }} {{ name }}! I am a Parent Component.
    <child-component message="Hi"></child-component>
  </div>
</template>

<script lang="ts">
type Props = {
  message: string;
};

import ChildComponent from "./Child.vue";

export default {
  name: "parent-component",
  components: { ChildComponent: ChildComponent },
  props: ["message"],

  data: () => ({ name: "Parent" }),
};
</script>

// apps/props/output/svelte/src/Parent.svelte
<script context="module" lang="ts">
  type Props = {
    message: string;
  };
</script>

<script lang="ts">
  import ChildComponent from "./Child.svelte";

  export let message: Props["message"];

  let name = "Parent";
</script>

<div>
  {message || "Hello"}
  {name}! I am a Parent Component.
  <ChildComponent {...props} />
</div>
