// apps/context/output/vue/vue3/src/Child.vue
<template>
  <div>
    {{ message || "Hello" }} {{ name }}! I am a Child component.
    {{ foo.foo }}
  </div>
</template>

<script setup lang="ts">
import { inject, provide, ref } from "vue";
type Props = {
  message: string;
};

import Context from "./custom.context.js";

const props = defineProps<Props>();
const name = ref("Child");

const foo = inject(Context);

provide(Context, undefined);
</script>

// apps/context/output/svelte/src/Child.svelte
<script context="module" lang="ts">
  type Props = {
    message: string;
  };
</script>

<script lang="ts">
  import { getContext, setContext } from "svelte";

  import Context from "./custom.context.js";

  export let message: Props["message"];

  let foo = getContext(Context.key);
  setContext(Context.key, {
    foo: "child",
    content() {
      return message;
    },
  });

  let name = "Child";
</script>

<div>
  {message || "Hello"}
  {name}! I am a Child component.
  {foo.foo}
</div>
