// apps/context/output/vue/vue3/src/Parent.vue
<template>
  <div>
    {{ message || "Hello" }} {{ name }}! I am a Parent Component.
    <child-component message="Hi"></child-component>
    {{ foo.foo }}
  </div>
</template>

<script setup lang="ts">
import { inject, provide, ref } from "vue";
type Props = {
  message: string;
};

import Context from "./custom.context.js";
import ChildComponent from "./Child.vue";

const props = defineProps<Props>();
const name = ref("Parent");

const foo = inject(Context);

provide(Context, undefined);
</script>

// apps/context/output/svelte/src/Parent.svelte
<script context="module" lang="ts">
  type Props = {
    message: string;
  };
</script>

<script lang="ts">
  import { getContext, setContext } from "svelte";

  import Context from "./custom.context.js";
  import ChildComponent from "./Child.svelte";

  export let message: Props["message"];

  let foo = getContext(Context.key);
  setContext(Context.key, {
    foo: "parent",
    content() {
      return message;
    },
  });

  let name = "Parent";
</script>

<div>
  {message || "Hello"}
  {name}! I am a Parent Component.
  <ChildComponent message="Hi" />
  {foo.foo}
</div>
