// apps/angular-standalone/output/angular/src/Child.ts
import { Component, Input } from "@angular/core";
import { CommonModule } from "@angular/common";

type Props = {
  message: string;
};

@Component({
  selector: "child-component, ChildComponent",
  template: `
    <div>{{message || "Hello"}} {{name}} ! I am a Child component.</div>
  `,
  standalone: true,
  imports: [CommonModule],
})
export default class ChildComponent {
  @Input() message: Props["message"];

  name = "Child";
}

// apps/show/output/react/src/Child.tsx
import * as React from "react";
import { useState } from "react";

type Props = {
  message: string;
};

export default function ChildComponent(props: Props) {
  const [name, setName] = useState(() => "Child");

  return (
    <div>
      {props.message || "Hello"}
      {name}! I am a Child component.
    </div>
  );
}
